package main

import (
	"bas-backend/config"
	_ "bas-backend/docs" // docs is generated by Swag CLI, you have to import it.
	"bas-backend/internal/app/http"
	"bas-backend/pkg/echo"
	"bas-backend/pkg/metrics"
	"context"

	"fmt"
	"log"
)

// @title Swagger Example API
// @version 1.0
// @description This is REST-API service for sk-bas.ru
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email admin@sk-bas.ru

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host 94.241.174.163/api/
func main() {
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("Could not load config: %v", err)
	}
	// Запуск сервера метрик на отдельном порту
	metricsPort := 9091 // или любое другое значение
	metrics.StartMetricsServer(metricsPort)

	ctx := context.Background()
	e := echo.New()

	http.RegisterRoutes(ctx, e, cfg)
	address := fmt.Sprintf(":%d", cfg.Server.Port)
	e.Logger.Fatal(e.Start(address))
}
